services:
  - type: web
    name: joe-hospital-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://root:plmokn00@cluster0.7deepnd.mongodb.net/joe-hospital
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 24h
      - key: JWT_REFRESH_EXPIRE
        value: 7d
      - key: CLIENT_URL
        value: https://joe-hospital.netlify.app